spring.application.name=agent
server.port=9090

# Logging Configuration
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.wiz.agent=DEBUG

# Agent Configuration
agent.id=6a7b8c9d0e
agent.version=1.0.0

# MQTT Configuration
mqtt.broker.url=tcp://15.206.61.50:1883
mqtt.client.id=4a4b4c4d4e
mqtt.broker.username=
mqtt.broker.password=

#Topic Configuration
broadcast.topic=agent/updates

#OpenHAB Configuration
openhab.url=http://localhost:8080
openhab.token=oh.Test.AQTNEu93h87toWvbRYKUi3tLyplgs1obQq2hW5XrNdHnbCEooK9Bv48b1qtWGMUtD1ysI937eQM6hYsH8Q